spring:
  application:
    name: app
  profiles:
    active: development

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

admin:
  password: ${ADMIN_PASSWORD}