server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update